### ISSUE TITLE
ORDER BY query quantifies given order by string (which might be an alias) with a table name

### ISSUE THREAD

**Issue by inkmix** [kayak/pypika#124]
**Example**
ORDER BY query using the alias without a join:
```
str(Query.from_(a).select(a.b, fn.Sum(a.c).as_('alias')).groupby(a.c).orderby('alias') )
=> 'SELECT "b",SUM("c") "alias" FROM "a" GROUP BY "c" ORDER BY "alias"'
```
ORDER BY query using the alias with a join:
```
str(Query.from_(a).join(b).on(a.b_id == b.id).select(a.foo, fn.Sum(a.int_column).as_('alias')).groupby(a.foo).orderby('alias') )
=> 'SELECT "a"."foo",SUM("a"."int_column") "alias" FROM "a" JOIN "b" ON "a"."b_id"="b"."id" GROUP BY "a"."foo" ORDER BY "a"."alias"'
```

**Issue**
The second example shows that when using a string in the `orderby` which might be an alias, is quantified with the FROM-table.

**Suggestion**
Don't quantify with the FROM-table in case of a string.
I think it's the coders responsibility to properly quantify, if necessary. The databases would complain for invalid SQL in case of ambiguous column names.

Let me know if there's a reason to quantify it that I don't see.

**Comment by inkmix** [comment]
(this would also apply to the `orderby` for `UnionQuery`)

**Comment by inkmix** [comment]
this can be solved by extracting the alias `alias = fn.Sum(a.int_column).as_('alias')` and reusing that in the select and order by clause.
thanks @twheys

**Comment by twheys** [comment]
In both examples, pypika is converting the string argument in `orderby(...)` to a field of table `'a'` because you used it in `from_(...)`. It's not intended to reference an alias, and I'm not sure how the database handles aliases that shadow column names.  In the second example, you've added a joined table so pypika prefixes all fields with the table name in the query string.

I think in this case it would be best to remove the behaviour of assuming strings are references to columns in the FROM table and treat them as raw strings in the SQL query instead.

**Comment by twheys** [comment]
the intended usage of this would be to pass in same value for orderby that you select, instead of a string with a matching alias, otherwise it's tricky for pypika to align. 

The following query will give you the correct result.
```
c = fn.Sum(a.c).as_('alias')
str(Query.from_(a).select(a.b, c).groupby(c).orderby(c))
```
