### ISSUE TITLE
BigQuery support

### ISSUE THREAD

**Issue by Berndvanderwielen** [kayak/pypika#132]
I'd love to see BigQuery support and with the following things in mind:

- cross joins
- select alias
- table alias
- table wildcards

**Comment by twheys** [comment]
Select and Table aliases are already supported if I'm understanding your request correctly. Cross joins would be pretty straight forward to implement. Based on reading https://cloud.google.com/bigquery/docs/querying-wildcard-tables I think table wildcards might already work, since pypika doesn't validate the table name, you could just add an asterisk in the table name and the rest should work the same.

I would suggest itemizing your requests and filing individual tickets for each one, otherwise the expectation of the ticket is unclear.

**Comment by Berndvanderwielen** [comment]
thanks for your reply. If I have any specific issue I will create a more concise entry. Will close.
