### ISSUE TITLE
QueryBuilder causing syntax error

### ISSUE THREAD

**Issue by gldavis3000** [kayak/pypika#179]
The querybuilder class defaults to:
INSERT INTO "table" ("col1","col2",etc)
I need
INSERT INTO table (col1,col2,etc)

I can't figure out how to get the query to build without quotes around table and column names.

**Comment by gldavis3000** [comment]
I can't change the QueryBuilder class code to make it default to having no quotes. I am deploying to AWS where I don't have access to the module code.
This should be something that can be set through some helper function or the Query __init__

**Comment by twheys** [comment]
The default behavior is to always use quotes, since that overcomes obstacles with using reserved words and special characters in a field. Different SQL dialects have different expectations, and there is some configuration to manage that.  You'll want to override the base `Query` class for your SQL dialect and override the `_builder` function to pass in the `quote_char` argument to the `QueryBuilder` class.

```
class MyDialectQuery(Query):
    @classmethod
    def _builder(cls):
        return QueryBuilder(quote_char=None)
```

Here is a more complicated example of a dialect for MySQL which uses a backtick character instead of double quotes: https://github.com/kayak/pypika/blob/master/pypika/dialects.py#L45

**Comment by twheys** [comment]
Would also be nice if you would contribute back your dialect implementation if you think others might find it useful.

**Comment by gldavis3000** [comment]
I tried what you have above.  I can import Query, Table, Field, etc, but when I try to import QueryBuilder I get "cannot find reference".  That is a pycharm inspection error.  Doesn't matter if I do "import pypika" or "from pypika import QueryBuilder".  I'm using pypika 0.16.1 so QueryBuilder definitely exists in queries.py.

I'm not sure what the dialect is. If it helps you know which one so you can share the info, we're using Amazon RDS.  Our company had a third party do our AWS setup because we don't have anyone with AWS experience.  I know the most, but I don't have permissions to view our RDS settings.

**Comment by twheys** [comment]
The QueryBuilder class is not exported in the pypika package. You'll need to import it like `from pypika.queries import QueryBuilder`.

"Dialect" is just the term we use to describe vendor specific SQL syntax. You'll want to create a QUERY class for your Platform. Here's a more complete example:


```
from pypika.queries import Query, QueryBuilder

class RDSQuery(Query):
    @classmethod
    def _builder(cls):
        return QueryBuilder(quote_char=None)

query = RDSQuery.from_( ... table ...).select('*')
```

**Comment by gldavis3000** [comment]
Thank you for the help.  I was able to resolve the problem this way.  The import system in python still throws me for a loop sometimes.
