### ISSUE TITLE
Pretty Formatting 

### ISSUE THREAD

**Issue by danfrankj** [kayak/pypika#194]
When using `get_sql` or `str` on a query object, it would be very helpful to have the option to format the results in a human readable format rather than as one long line. 

Do you think this is a feature that belongs in this library?

**Comment by twheys** [comment]
Not necessarily because there are several existing utilities for doing this that can be used directly on the results of `get_sql`. By offering this in pypika, we wouldn't be offering much convenience, at the expense of assuming how the formatting should be done.

I have one case where I do this. I use [sqlparse](https://pypi.org/project/sqlparse/) for it: `sqlparse.format(str(query))`
