### ISSUE TITLE
Support for empty `isin` value

### ISSUE THREAD

**Issue by jtrain** [kayak/pypika#226]
When building a query like

`MyTable = Table('demo'); Query.from_(MyTable).where(MyTable.id.isin(value)).select(MyTable.id)`

and `value = []` the sql is generated:

`SELECT "demo"."id" FROM "demo" WHERE "demo"."id" IN ()`

of which the `IN ()` is invalid for a Postgres database.

It would be nice if somehow we could prevent emitting the IN filter in cases where the `value` was empty.

The reason I'd like that, is it would behave similarly to django's queryset which won't generate the invalid SQL, and the code I have managing the differences could be removed.

For options to solve this I see two:

1. We could check `values` before putting them into pypika queries in our own code; or
2. pypika could do additional validation on inputs to prevent this particular user mistake.

The downsides to 2) would be that all pika code now carries the burden of this extra validation, and perhaps other similar validations down the line.

I'm happy to generate a PR if there is interest

**Comment by twheys** [comment]
One of the goals with pypika is to avoid validating the queries, since the behavior of different databases can be wildly different. In this case, Pypika will generate a query as it was built, with an empty `IN` clause since an empty list was passed in the query. Executing the query will result in the error which can be handled at that stage.

**Comment by jtrain** [comment]
No worries, I've got code validating input before I call pypika.
