### ISSUE TITLE
Type-hinting 

### ISSUE THREAD

**Issue by Rested** [kayak/pypika#323]
Type hinting would be really awesome on this project. If you think it's a good idea @twheys  I would be happy to work on adding it.

**Comment by mikeengland** [comment]
@Rested we'd love to have your contribution! Feel free to add type hints and raise a PR and we'll take a look.

**Comment by nsidnev** [comment]
@mikeengland, hi!
Since this issue has been inactive for several months, I've added type-hints for the `pypika.queries` and `pypika.terms` modules (as a start point) to [this](https://github.com/nsidnev/pypika/tree/add-type-hints) branch in my fork. I'd like to open a PR for this, but the resulting diff is too large (althogh only type annotations were affected there). I can split this into several PRs (per file or class, for example) or open with the current branch if this is OK for you.

**Comment by Rested** [comment]
Hey @nsidnev thanks for taking this up! Got distracted by an issue with autocomplete when trying to implement the typing for the builder decorator https://github.com/davidhalter/jedi/issues/1413 which seemed necessary for nice autocompletion during use. Your branch looks good and once it's merged ill try to make some time to come back and have a look at the builder decorator :+1:

**Comment by mikeengland** [comment]
Hi @nsidnev, thanks for looking into this!

It would be good to raise multiple PRs for ease of review (per file is fine). I noticed that you also did some Black formatting which will make the diff very large. I am not sure if it is possible to leave out the formatting for now (not an issue if your changes are intertwined). We have an old PR in place to setup Black, but I may set this up myself again soon.

**Comment by nsidnev** [comment]
> We have an old PR in place to setup Black, but I may set this up myself again soon.

Adding Black to pypika would be great. Maybe it's worth adding isort/autoflake as well?

> It would be good to raise multiple PRs for ease of review (per file is fine).

Ok, then I'll raise 3 PRs:
1. for `pypika.enums` and `pypika.utils`, which will be small
2. for `pypika.terms`
3. for `pypika.queries`

I'll also try to remove black formatting where I can.

**Comment by nsidnev** [comment]
@Rested, my current changes were merged! I'll be glad to see your changes to the `builder` decorator.

@mikeengland 
The `pypika.analytics`, `pypika.functions`, `pypika.dialects` and `pypika.clickhouse` were left without typings. Changes in `pypika.dialects` and `pypika.clickhouse` I can send tomorrow.  I'm not sure if `pypika.analytics` and `pypika.funcions` should be typed, but can do this as well. And I'm sure that some typings are not quite right, so they should be gradually improved.

It would also be nice to add a `py.typed` marker (per [PEP 561](https://www.python.org/dev/peps/pep-0561/)) to allow `mypy` to find `pypika`. But IMO, this should be done after merging #361, since `poetry` will handle this automatically.
