### ISSUE TITLE
limit zero not supported when argument is int

### ISSUE THREAD

**Issue by StephenCarboni** [kayak/pypika#368]
```python
from pypika import Query

q = Query.from_('foo').select("bar")
q2 = q.limit(0)
q3 = q.limit('0')

print(q, q2, q3, sep='\n')

```

```
SELECT "bar" FROM "foo"
SELECT "bar" FROM "foo"
SELECT "bar" FROM "foo" LIMIT 0
```

q2 is missing it's LIMIT 0

**Comment by airtonzanon** [comment]
Hello @StephenCarboni. 

That happens because you're doing the limit by zero. As zero is interpreted as false on python, it'll not understand that you're limiting by zero, but by false.

It happens because of how it's implemented the limit function on PyPika. it'll verify if the limit value exists and then do the limit. So if it's zero, it'll understand as the limit value is false.

I would recommend you using string to limit it by zero if it's really necessary. I don't know if the effort to accept zero as an integer on the limit worth it.

But you can limit with other numbers, like:

```python
from pypika import Query

q = Query.from_('foo').select("bar")
q2 = q[:10]
q3 = q.limit(10)

print(q, q2, q3, sep='\n')
```

The result will be:

```sql
SELECT "bar" FROM "foo"
SELECT "bar" FROM "foo" LIMIT 10
SELECT "bar" FROM "foo" LIMIT 10
```

**Comment by elrik75** [comment]
`LIMIT 0` is SQL valid. Do not forget that we all use pypika to forge queries dynamically, and it's fully acceptable to allow `0` as it's valid. Also the patch seems very trivial: replace all `if self._limit:` and `if self._offset:` by `if self._limit is not None` and `if self._offset is not None`, right ?
