### ISSUE TITLE
Inconsistent table qualifiers

### ISSUE THREAD

**Issue by benjaminsanborn** [kayak/pypika#381]
Hey all; thanks for the library! I'm doing a lot of composition work and I've discovered that when I compose a query as below:

```
>>> from pypika import Query, Table, Field, BasicCriterion
>>> from pypika.terms import BasicCriterion, ValueWrapper, Equality
>>> Query().from_(Table("amtrak")).select(Field("id", table=Table("amtrak"))).where(BasicCriterion(Equality.eq, Field("id", table=Table("amtrak")), ValueWrapper(1))).limit(5).offset(18)
```
it prepares:
```
SELECT "id" FROM "amtrak" WHERE "id"=1 LIMIT 5 OFFSET 18
```

However, when I re-order the application,
```
>>> Query().select(Field("id", table=Table("amtrak"))).where(BasicCriterion(Equality.eq, Field("id", table=Table("amtrak")), ValueWrapper(1))).from_(Table("amtrak")).limit(5).offset(18)
```
it produces:
```
SELECT "amtrak"."id" FROM "amtrak" WHERE "amtrak"."id"=1 LIMIT 5 OFFSET 18
```

I'm going to use the fully-validated second case, but I'm wondering, is the former behavior a bug or trying to eliminate the table name calls?

**Comment by twheys** [comment]
I think the issue with your second query is because you're using different table names, which pypika might be able to validate for. Is there a reason why you're importing all these internal classes and using them directly, like BasicCriterion and ValueWrapper? Would recommend writing these as follows:

```
amtrak = Table("amtrak")
print(
    Query().from_(amtrak)
        .select(amtrak.id)
        .where(amtrak.id == 1)
        .limit(5)
        .offset(18)
)
```
 
```
amtrak_v3 = Table("v3_Amtrak")
print(
    Query.select(amtrak_v3.id)
        .from_(amtrak_v3)
        .where(amtrak_v3.id == 1)
        .limit(5)
        .offset(18)
)
```
Can you try to refactor your code and see if that fixes the issue?

**Comment by benjaminsanborn** [comment]
Oops, sorry the table name issue was just a typo; I've updated the comment. I'm using all the explicit classes since these expressions are being dynamically generated in our code, so I have some methods explicitly generating instances of `BasicCriterion` etc.

I'll play around with the `BasicCriterion` bit, thanks for the recommendation.

I guess more generally, if I execute the first one you mentioned:
```
>>> amtrak = Table("amtrak")
>>> print(
...     Query().from_(amtrak)
...         .select(amtrak.id)
...         .where(amtrak.id == 1)
...         .limit(5)
...         .offset(18)
... )
SELECT "id" FROM "amtrak" WHERE "id"=1 LIMIT 5 OFFSET 18
```
Is there a reliable way to get `"id"` be called as `"amtrak"."id"`? I want to be able to do that so I can avoid collisions when I compose queries with `.join()`.

**Comment by benjaminsanborn** [comment]
here's a simpler example of the issue I'm trying to isolate:
```
>>> from pypika import Query, Table
>>> amtrak = Table("amtrak")
>>> Query().from_(amtrak).select(amtrak.id).where(amtrak.id == 1)
SELECT "id" FROM "amtrak" WHERE "id"=1
>>> Query().select(amtrak.id).where(amtrak.id == 1).from_(amtrak)
SELECT "amtrak"."id" FROM "amtrak" WHERE "amtrak"."id"=1
```

**Comment by twheys** [comment]
If you join tables in your query, pypika adds the table prefix in order to force disambiguation, but in this case it appears to be a bug because you only have one table. I thought changing the syntax to have on reference to the table *might* at least give you a workaround but if you're still getting the same result then unfortunately that's not the case.

This will require a code change in pypika to fix. I can take a look in the coming days.
