### ISSUE TITLE
control over tablename prefix in `with_` then `select`

### ISSUE THREAD

**Issue by zkurtz** [kayak/pypika#382]
This kind of thing would throw an ambiguous column exception for column `key`:
```
from pypika import AliasedQuery, Query, Table

a_table = Table('a')
a_query = Query.from_(a_table).select('acol, key, sharedcolumn')

b_table = Table('b')
b_query = Query.from_(b_table).select('bcol, key, sharedcolumn')

withed_a = AliasedQuery('a')
withed_b = AliasedQuery('b')
qx = (Query.
    with_(a_query, 'a').
    with_(b_query, 'b').
    from_(withed_a).
    select('acol, key').
    join(withed_b).
    on_field('sharedcolumn')
)

################
## Result:
WITH a AS
  (SELECT acol,
          key,
          sharedcolumn
   FROM a),
     b AS
  (SELECT bcol,
          key,
          sharedcolumn
   FROM b)
SELECT a.acol,
       key
FROM a
JOIN b ON a.sharedcolumn=b.sharedcolumn
```

The hack I have to get around this is extremely ugly. Is there a graceful way to specify the result 'key' vs 'a.key' vs 'b.key' in the select statement?

**Comment by twheys** [comment]
Hi!
You shouldn't be calling the select method with a comma delimited list of names, rather a list of strings or pypika `Field` objects,

like:
```
a_table = Table('a')
a_query = Query.from_(a_table).select('acol', 'key', 'sharedcolumn')
 --- OR ---
a_query = Query.from_(a_table).select(a_table.acol, a_table.key, a_table.sharedcolumn)
```

You can also reference fields from queries by accessing attributes directly on the query objects themselves

```
qx = (Query.
    .with_(a_query, 'a')
    .with_(b_query, 'b')
    .from_(withed_a)
    .select(withed_a.acol)
    .select(withed_a.key.as_('akey'))
    .join(withed_b)
    .on_field('sharedcolumn')
    .select(withed_b.key.as_('bkey'))
)
```

**Comment by zkurtz** [comment]
Thanks @twheys for correcting my usage. This helps to an extent, but my incorrect usage might have been a distraction from my underlying concern which I should have elaborated better and has multiple facets.

Suppose instead of the actual variable names I want to pass in a list of variable names and query them all from table b. Is there any more graceful way to do it than this for list [x, y, z]?:

```
B_COLS = ['x', 'y', 'z']
a_table, b_table = Table('a'), Table('b')
a_query = Query.from_(a_table).select('w, sharedcolumn')
b_query = Query.from_(b_table).select(*B_COLS + ['sharedcolumn'])
withed_a, withed_b = AliasedQuery('a'), AliasedQuery('b')
qx = (Query.
    with_(a_query, 'a').
    with_(b_query, 'b').
    from_(withed_a).
    select(withed_a.w).
    select(*[getattr(withed_b, col) for col in B_COLS]).
    join(withed_b).
    on_field('sharedcolumn')
)
```
So that might be just a question of style, but a more serious concern that a simple operation like
 `select('a.w + b.x as wx')` prepends a tablename that I did not intend to request: `a.a.w + b.x AS wx`

Maybe a more "correct" way to do that is `select(withed_a.w + withed_b.x).as_('wx')`?? But in this case, 'as_' gets ignored. Is this related to https://github.com/kayak/pypika/issues/383 ?

**Comment by twheys** [comment]
By using references to Field objects, pypika can distinguish which table or nested query that field points to, which was the answer to the first question 

> The hack I have to get around this is extremely ugly. Is there a graceful way to specify the result 'key' vs 'a.key' vs 'b.key' in the select statement?

Regarding the other questions:

> Is there any more graceful way to do it than this for list [x, y, z]?
Since pypika leans on the python syntax, no not really, although you can use index notation instead of dot notation to avoid the need for `getattr`. That makes syntax a bit cleaner.
```
 ... .select(*[withed_b[col] for col in B_COLS])
```

> So that might be just a question of style, but a more serious concern that a simple operation like
select('a.w + b.x as wx') prepends a tablename that I did not intend to request: a.a.w + b.x AS wx
>
> Maybe a more "correct" way to do that is select(withed_a.w + withed_b.x).as_('wx')?? 

Pypika does not interpret strings passed into select as expressions, only as fields of the table (or subquery) used in the FROM clause of the query. You'll need to use the pypika python objects for that. Here's the syntax you want
```
wx = (a.w + b.x).as_('wx')
... .select(wx)
```
The addition expression returns a pypika object which has the `as_` method on it to set an alias. If you call `as_` on the return value of the `Query.select()` method you'll apply an alias to the query object, which would show up if you nested that query in another query.

**Comment by zkurtz** [comment]
Thanks much. Awesome project.
