### ISSUE TITLE
"AS" alias in SQL

### ISSUE THREAD

**Issue by woochan-cho** [kayak/pypika#390]
Hi. I am not sure if I can ask you a question. However please give me a favor.
When I see the previous sample code, there is "AS" when use column alias.

q = Query.from_(accounts).select(
    (accounts.revenue - accounts.cost).as_('profit')
)
_SELECT revenue-cost **AS** 'profit' profit FROM accounts_

But, now I can't find it and also I can't find "AS" any more when I run the code. 

_SELECT revenue-cost  'profit' profit FROM accounts_

How I can make it show in the resulting query please?

**Comment by twheys** [comment]
Hi! The "AS" keyword is omitted for brevity. I haven't seen a flavor of SQL where it's required. Do you have a use case where it's necessary?

**Comment by elrik75** [comment]
Since 0.36.2, there are nested aliases. This broken all my `clickhouse` queries. https://clickhouse.tech/docs/en/

But if I can add the "AS" keywork it works again.

Before: 0.36.2, it worked:
`AVG(if("field"='value', "field"-"startTime", NULL)) "alias.avg"`

With 0.36.2, it now crashes:
`AVG(if("field"='value', "field"-"startTime", NULL) "needted_alias") "alias.avg"`

With the "AS" it works again:
`AVG(if("field"='value', "field"-"startTime", NULL) AS "needted_alias") AS "alias.avg"`

So for `Clickhouse`, it would help if we can add the "AS" or optionaly disable nested aliases.

Thanks

**Comment by lntuition** [comment]
Hello :) We support with nested alias by need due to issue #388 (And this seems reasonable)
With your example, `AS` keyword seems to be essential (And also seems reasonable, too)

@elrik75 Before reveiwing this issue, could you show me your pypika phrase?

**Comment by lntuition** [comment]
```python3

def test_function_using_as_nested(self):
    q = Query.from_(self.t).select(fn.Sqrt(fn.Count("*").as_("foo")).as_("bar"))

    self.assertEqual('SELECT SQRT(COUNT(*) "foo") "bar" FROM "abc"', str(q))

def test_function_using_as_nested_outer_only(self):
    q = Query.from_(self.t).select(fn.Sqrt(fn.Count("*")).as_("bar"))

    self.assertEqual('SELECT SQRT(COUNT(*)) "bar" FROM "abc"', str(q))
```

Looking at the above TC(both are successful), your problem seems to be solved by removing the internal `as_`

**Comment by jeremy-feng** [comment]
Hi PyPika Team,

I need the `AS` keyword to be included in the SQL for column aliases. Using the `as_()` method doesn't include the `AS` keyword in the generated SQL. How can I achieve this?

Here’s my current code:
```python
from pypika import Query, Table

table = Table('my_table')
query = Query.from_(table).select(
    table.field1.as_('alias1'),
    table.field2.as_('alias2')
)
print(query)
```

Current output:
```sql
SELECT "field1" "alias1", "field2" "alias2" FROM "my_table"
```

Desired output:
```sql
SELECT "field1" AS "alias1", "field2" AS "alias2" FROM "my_table"
```

Thanks！
