### ISSUE TITLE
Oracle concatenate fields

### ISSUE THREAD

**Issue by steelunicorn** [kayak/pypika#393]
Hello.

I'm trying to use ORA_HASH function on all table fields. Is there any way to do it with pypika? 
As a result I want to get something like:
`SELECT ORA_HASH("FIELD_A"||"FIELD_B"||"FIELD_C") AS "HASH", "FIELD_A", "FIELD_B", "FIELD_C" FROM "TABLE1"`

**Comment by twheys** [comment]
Hi. Usually you can create an instance of the pypika Function class using the factory class https://github.com/kayak/pypika/blob/cce2435b101870d6b82b2c80bd8a4d96bc6aaf93/pypika/terms.py#L1077

Since your function has some deviating syntax, the pipe characters between args, I would recommend instead creating a Function subclass and overriding the `get_sql` function like the following example:

```
from pypika.functions import Function

class OraHash(Function):

     def __init__(fields):
        self.fields = fields
    def get_sql(**kwargs):
        return '||'.join(field.get_sql(**kwargs) for field in self.fields)
```

Check out https://github.com/kayak/pypika/blob/cce2435b101870d6b82b2c80bd8a4d96bc6aaf93/pypika/functions.py for more examples
