### ISSUE TITLE
Parameters with Where syntax

### ISSUE THREAD

**Issue by andreamoro** [kayak/pypika#440]
I must have been missing something, but in doing something like

```
q = Query.from_(table) \
    .select(table.attribute) \
    .where(Tuple(table.parent, table.chain, table.attribute)) \
    .insert(Parameter('?'), Parameter('?'), Parameter('?'))
```

I get the ```AttributeError: 'Query' object has no attribute 'insert'``` error. No valid documentation to use the Parameters in a where clause, which I think it's useful.

**Comment by BobForCat** [comment]
Hi
The problem comes from your query, you cannot mix a `SELECT` query (read results) and an `INSERT` (write results) query

Here are the documentation pages that'll help you
- [`SELECT`](https://pypika.readthedocs.io/en/latest/2_tutorial.html#selecting-data)
- [`INSERT`](https://pypika.readthedocs.io/en/latest/2_tutorial.html#inserting-data)

To insert into you table using a [`Parametrized` query](https://pypika.readthedocs.io/en/latest/2_tutorial.html#parametrized-queries) do

```python
table = Table("mytable")
q = table.columns(table.parent, table.chain, table.attribute).insert(Parameter('?'), Parameter('?'), Parameter('?'))

# then execute
sqlengine.execute(q.get_sql(), ("parent1", "chain1", "attrib1"))

```

**Comment by mikeengland** [comment]
Thanks for assisting @BobForCat

**Comment by andreamoro** [comment]
Thanks. Apologies for the delay, but I missed the answer in first instance..
