### ISSUE TITLE
How to escape characters in the LIKE operator

### ISSUE THREAD

**Issue by andreamoro** [kayak/pypika#500]
Hello there,

There shouldn't be any need to escape things in a LIKE operator, but as a matter of fact a where condition like this `.where(a.ATTRIBUTE.like("{%"))` generates an output like `AND "a"."ATTRIBUTE" LIKE \'{%\''` which fails by saying I don't have a closing }.

```
Exception has occurred: ValueError
expected '}' before end of string
```

As a matter of fact the `{` has to be part of the search string and I'm not sure how to get this through. 

The  self.wrap_constant(expr) seems to be the one function responsible for the wrapping bit, but I don't think it's the one causing the issue. 

The produced query, when ran past an sqLite3 IDE returns results as expected.

![image](https://user-images.githubusercontent.com/5256583/95765054-985e6580-0cb1-11eb-927b-daeddca6faaa.png)

Any idea, fix?

**Comment by andreamoro** [comment]
@BobForCat @mikeengland any ideas of what I'm doing wrong?

**Comment by mikeengland** [comment]
Hi @andreamoro. This looks due to the quote_char in use. What database platform are you using? The Query classes have different quote_chars specified. You can see this in effect here. The following lines show results without escaping.

`
tbl = Table('tbl')

Query.from_(tbl).select(tbl.test).where(tbl.ATTRIBUTE.like('{%')).get_sql(quote_char=None)
"SELECT test FROM tbl WHERE ATTRIBUTE LIKE '{%'"

Query.from_(tbl).select(tbl.test).where(tbl.ATTRIBUTE.like('{%')).get_sql(quote_char="'")
"SELECT 'test' FROM 'tbl' WHERE 'ATTRIBUTE' LIKE '{%'"
`

**Comment by andreamoro** [comment]
Thanks Mike,  I'm using sqLite3 in this occasion.

I don't understand though why by doing the above worked. 

The logic would suggest a replacement of the quote in the LIKE argument from ' to " to work too, but - in fact - it did not when I tried yesterday. 

Is the call quote_char argument best called in the get_sql method, or would that be preferable call during class initiation?

**Comment by mikeengland** [comment]
Really the best approach is to use a parameterized query which would solve your problem.

See https://github.com/kayak/pypika#parametrized-queries

`Query.from_(tbl).select(tbl.test).where(tbl.ATTRIBUTE.like(Parameter('%(attr_value)'))).get_sql()`. You can then pass attr_value='{%' in as a parameter to your database driver. See your database driver docs for more details.

**Comment by andreamoro** [comment]
Thanks. 
I was already using the parameters for the other two likes above, but didn't implement for the last one as there where no need of such a flexibility.
But it's welcome if it solves a number of headaches.
