### ISSUE TITLE
Clickhouse dialect

### ISSUE THREAD

**Issue by kszucs** [kayak/pypika#67]
I'd like to use fireant with clickhouse database, but I could not find an easy way to extend pypika with another sql backend. What is the recommended way?

**Comment by twheys** [comment]
Hi, right now the dialects are in pypika.queries, but I'll move them into a new dialects module to make them easier to find. You can use them as an example.  In most cases, pypika doesn't need to be extended any in order to support a SQL database, but there are sometimes differences in syntax.  For example mysql uses a backtick for a quote character.  I'm not familiar with Clickhouse but I'd be happy to help you get pypika to work for it.

Try using `pypika.Query` to build queries.  If the quote character is different (like in mysql), then we can create a dialect class like in `pypika.dialects` (in my PR).  If the syntactic differences are more than that we might need to adapt pypika a bit to support the differences.

**Comment by kszucs** [comment]
Well, clickhouse uses mysql quote chars, but [doesn't use](https://clickhouse.yandex/docs/en/introduction/distinctive_features.html#sql-support) standard SQL, there are a lot of [custom clauses](https://clickhouse.yandex/docs/en/query_language/queries.html#select), [functions](https://clickhouse.yandex/docs/en/functions/index.html), [aggregations](https://clickhouse.yandex/docs/en/agg_functions/index.html) and limitations (e.g. only one JOIN can be specified in a query - on a single level).

Can pypika adapt that well?

**Comment by twheys** [comment]
Yes, pypika doesn't enforce any restrictions on which functions can be defined or used (but obviously the functions won't work for database vendors that don't support them).  It includes a lot of functions which are part of the ANSI standard, but not exhaustively.

Take a look at https://github.com/kayak/pypika/blob/master/pypika/functions.py for examples of how to implement functions and https://github.com/kayak/pypika/blob/master/pypika/analytics.py for examples of analytic functions.

Examples of creating a Dialect wrappers can be found in my open PR https://github.com/kayak/pypika/pull/68/files#diff-3e0f8605653b7b954801ec8ac584e7d4 - If you'd like to contribute one for Clickhouse, please open another PR. Right now the dialects are quite basic but potentially any behavior can be overridden.

I can't promise that everything doable in Clickhouse is immediately supported by pypika, but if you run into any barriers, please feel free to create tickets to support them.

Regarding restrictions such as the limit to the number of joins: pypika doesn't enforce any of these kind of rules because the database itself will enforce them.
